### ISSUE TITLE
when trying to run the application I get out and log 

### ISSUE THREAD

**Issue by drneox** [jimjeffers/rails-devise-cors-jwt-example#1]
{"error":"You need to sign in or sign up before continuing."}

**Comment by jimjeffers** [comment]
Can you add more context? What is the request you're sending to get that response?

**Comment by scottbaggett** [comment]
What is the route to POST to to sign in?  POST /users/sign_in returns

```
{"error":"You need to sign in or sign up before continuing."}
```

**Comment by jimjeffers** [comment]
I've updated the example to allow for JSON based registration and updated the readme and JSON based responses so you should be able to authenticate successfully via JSON requests. This example was more so focused on how to properly verify the JWT and didn't cover the minimal setup required to make JSON based session creation / registration work.

**Comment by scottbaggett** [comment]
Much appreciated!

**Comment by jimjeffers** [comment]
@scottbaggett for more info on configuring Devise for JSON based sessions see this excellent post:
http://blog.andrewray.me/how-to-set-up-devise-ajax-authentication-with-rails-4-0/

**Comment by scottbaggett** [comment]
WIll do, thanks again. :)
